[package]
name = "acey-ducey"
version = "0.1.0"
authors = ["Andrew Kuchling <amk@amk.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
